#cloud-config
hostname: ${WORKER_VM_NAME}
manage_etc_hosts: false

runcmd:
  # Make sure kubelet is running
  - systemctl enable kubelet
  - systemctl start kubelet

  # Make sure control plane hostname is resolvable
  - echo "${CONTROL_PLANE_IP} ${CONTROL_PLANE_VM_NAME}" >> /etc/hosts
  - cat /etc/hosts

  # Wait for control plane to become available
  - until nc -z ${CONTROL_PLANE_ENDPOINT} 6443; do echo "Waiting for control plane ${CONTROL_PLANE_ENDPOINT}..."; sleep 10; done

  # Join the Kubernetes cluster
  - eval "$JOIN_COMMAND --ignore-preflight-errors=NumCPU,Mem"
  - echo "Kubernetes eval join command executed"
  - bash -c "${JOIN_COMMAND} --ignore-preflight-errors=NumCPU,Mem"
  - echo "Kubernetes bash -c join command executed"
